# Generated by Django 3.1 on 2020-10-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_playing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing',
            name='date',
            field=models.DateField(verbose_name='playing date'),
        ),
    ]
