# Generated by Django 3.1 on 2020-10-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201023_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
    ]
